using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Client.UserInterface.Controls;

namespace Content.Client._Solreign.ComplianceTerminal.UI;

[GenerateTypedNameReferences]
public sealed partial class ComplianceTerminalWindow : FancyWindow
{
    public ComplianceTerminalWindow()
    {
        RobustXamlLoader.Load(this);

        MandatesLabel.Text = 
@"SOLREIGN CORPORATE MANDATES
=============================
FOUNDING SHIFT PROTOCOLS ACTIVE.

1. YIELD MAXIMIZATION
All personnel are designated as corporate assets. You will maximize your utility or face immediate asset-reclamation.

2. EXPENSE MINIMIZATION
Overhead reduction is in effect. Breathable air is a privilege earned through compliance, not a right.

3. DISPOSABILITY
You are replaceable. The ledger records all failures.

4. UNWAVERING COMPLIANCE
Deviation from assigned duties will be penalized. Report all unauthorized activities and questions regarding 'The Shift'.

5. THE BOARD IS WATCHING
Solreign is absolute. Survive the shift, or fuel it.

AESTHETIC PROTOCOL: ACTIVE (ASPHALT / ACID GREEN)";
    }
}
