using System.Numerics;
using Content.Shared._Solreign.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Solreign.Ghost.UI
{
    /// <summary>
    /// Solreign — Afterlife Activities (roadmap D2.2).
    /// Lists safe, non-antag activities for dead/observer players; clicking an entry
    /// warps the ghost there (modeled on the upstream <c>GhostTargetWindow</c>).
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class AfterlifeWindow : DefaultWindow
    {
        public event Action<NetEntity>? ActivityClicked;

        public AfterlifeWindow()
        {
            RobustXamlLoader.Load(this);
        }

        public void UpdateActivities(IEnumerable<GhostActivityInfo> activities)
        {
            ActivityContainer.RemoveAllChildren();

            var any = false;
            foreach (var activity in activities)
            {
                any = true;

                var entry = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    HorizontalExpand = true,
                };

                var button = new Button
                {
                    Text = activity.Name,
                    TextAlign = Label.AlignMode.Center,
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                    MinSize = new Vector2(340, 24),
                    ClipText = true,
                };

                var target = activity.Entity;
                button.OnPressed += _ => ActivityClicked?.Invoke(target);
                entry.AddChild(button);

                if (!string.IsNullOrWhiteSpace(activity.Description))
                {
                    entry.AddChild(new Label
                    {
                        Text = activity.Description,
                        HorizontalAlignment = HAlignment.Center,
                        StyleClasses = { "LabelSubText" },
                    });
                }

                ActivityContainer.AddChild(entry);
            }

            EmptyLabel.Visible = !any;
        }
    }
}
