using System;
using Content.Client.UserInterface.Controls;
using Content.Shared._Solreign.Records;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._Solreign.Records.UI;

/// <summary>
///     Personnel Records Terminal window body: renders whatever
///     <see cref="RecordsTerminalSnapshot"/> the server last pushed. Every field is already-rendered
///     display text (the Contracts Board "dumb terminal" idiom) — this control does no copy
///     selection of its own beyond the empty-state fallbacks for the two nullable/emptyable fields
///     (<see cref="RecordsTerminalSnapshot.SocialFirsts"/>, <see cref="RecordsTerminalSnapshot.MarkLine"/>).
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RecordsTerminalWindow : FancyWindow
{
    public event Action? OnRefreshPressed;

    public RecordsTerminalWindow()
    {
        RobustXamlLoader.Load(this);

        RefreshButton.OnPressed += _ => OnRefreshPressed?.Invoke();
    }

    public void UpdateSnapshot(RecordsTerminalSnapshot snapshot)
    {
        TitleLabel.Text = snapshot.Title;
        ToursLabel.Text = snapshot.Tours.ToString();
        StandingLabel.Text = snapshot.Standing;
        FirstDeathLabel.Text = snapshot.FirstDeathStatus;
        MarkLabel.Text = snapshot.MarkLine ?? Loc.GetString("solreign-records-terminal-mark-none");

        SocialFirstsContainer.Children.Clear();
        if (snapshot.SocialFirsts.Count == 0)
        {
            SocialFirstsContainer.AddChild(new Label { Text = Loc.GetString("solreign-records-terminal-social-none") });
        }
        else
        {
            foreach (var line in snapshot.SocialFirsts)
                SocialFirstsContainer.AddChild(new Label { Text = line });
        }
    }
}
