using Content.Client.UserInterface.Controls;
using Content.Shared._Solreign.Market;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Solreign.Market.UI;

/// <summary>
///     The "Requisitions Anonymous" window body: rebuilds the card list on every state push, the
///     Contracts Board <c>SolreignContractsBoardMenu.UpdateEntries</c> idiom. Per-card Buy events
///     bubble up as an int-id event for the BUI to turn into a <see cref="SolreignMarketBuyMessage"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SolreignMarketMenu : FancyWindow
{
    public Action<int>? OnBuyPressed;

    public SolreignMarketMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateEntries(List<SolreignMarketListing> listings, string statusText)
    {
        ListingEntriesContainer.Children.Clear();

        StatusLabel.Visible = statusText.Length > 0;
        StatusLabel.Text = statusText;

        NoListingsLabel.Visible = statusText.Length == 0 && listings.Count == 0;

        foreach (var listing in listings)
        {
            var entry = new SolreignMarketEntry(listing);
            entry.OnBuyPressed += () => OnBuyPressed?.Invoke(listing.Id);

            ListingEntriesContainer.AddChild(entry);
        }

        ListingEntriesContainer.AddChild(new Control
        {
            MinHeight = 10
        });
    }
}
