using Content.Client.Message;
using Content.Shared._Solreign.Market;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Solreign.Market.UI;

/// <summary>
///     One black-market listing card. Copies the <c>SolreignContractEntry</c> idiom, minus the
///     prototype-driven name/description resolution: the daemon's (already length-capped, see
///     <c>SolreignMarketSystem.SanitizeListings</c>) flavor name/description ARE the display text,
///     so they are rendered directly — but STILL run through
///     <see cref="FormattedMessage.EscapeText"/> before hitting a markup-parsing label, the same
///     defense every other untrusted-string-in-a-RichTextLabel spot in this codebase uses
///     (Examine item names, chat author names, etc): a sanitized length is not the same guarantee
///     as "contains no markup", and this text originates outside this game entirely (the Director
///     daemon's LLM-authored flavor).
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SolreignMarketEntry : BoxContainer
{
    public Action? OnBuyPressed;

    public SolreignMarketEntry(SolreignMarketListing listing)
    {
        RobustXamlLoader.Load(this);

        NameLabel.SetMarkup(Loc.GetString("solreign-market-ui-name-label",
            ("name", FormattedMessage.EscapeText(listing.Name))));
        PriceLabel.SetMarkup(Loc.GetString("solreign-market-ui-price-label", ("price", listing.Price)));

        if (listing.Description.Length == 0)
        {
            DescriptionSeparator.Visible = false;
        }
        else
        {
            DescriptionLabel.SetMarkup(Loc.GetString("solreign-market-ui-description-label",
                ("description", FormattedMessage.EscapeText(listing.Description))));
        }

        BuyButton.Disabled = listing.IsSold;
        BuyButton.Text = listing.IsSold
            ? Loc.GetString("solreign-market-ui-sold-button")
            : Loc.GetString("solreign-market-ui-buy-button");

        BuyButton.OnPressed += _ => OnBuyPressed?.Invoke();
    }
}
