using System;
using System.Collections.Generic;
using Content.Client.UserInterface.Controls;
using Content.Shared._Solreign.Bounties;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Solreign.Bounties.UI;

/// <summary>
///     The Liability Board window body. Two independent update surfaces, both driven by the same
///     <see cref="SolreignBountyUiState"/> push: the row list (Contracts Board
///     <c>UpdateEntries</c> idiom — rebuild on every state) and the claim input (Directive
///     Terminal <c>SolreignOracleWindow</c> idiom — live length clamp + disabled-until-valid
///     submit). Client-side clamping here is UX only; the server enforces the real cap
///     independently (see <c>BountyClaimRules.MaxClaimTextLength</c>).
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SolreignBountyBoardWindow : FancyWindow
{
    /// <summary>Mirrors <c>BountyClaimRules.MaxClaimTextLength</c> (Content.Server) — UX convenience only, never the authority.</summary>
    public const int MaxClaimTextLength = 300;

    public event Action<string>? OnClaimSubmitted;

    public SolreignBountyBoardWindow()
    {
        RobustXamlLoader.Load(this);

        ClaimInput.OnTextChanged += OnClaimTextChanged;
        ClaimInput.OnTextEntered += _ => TrySubmit();
        SubmitButton.OnPressed += _ => TrySubmit();

        UpdateCharCount();
        UpdateSubmitEnabled();
    }

    public void UpdateState(List<SolreignBountyListing> bounties, string? status, bool offline = false)
    {
        BountyEntriesContainer.Children.Clear();
        // ALIVENESS P0 #2: offline (fetch failed) and true-empty (successful, empty pool) are
        // distinct states with distinct copy — never render the empty line while offline.
        NoBountiesLabel.Visible = !offline && bounties.Count == 0;
        OfflineLabel.Visible = offline;

        foreach (var listing in bounties)
            BountyEntriesContainer.AddChild(new SolreignBountyEntry(listing));

        BountyEntriesContainer.AddChild(new Control
        {
            MinHeight = 10
        });

        StatusLabel.Visible = !string.IsNullOrEmpty(status);
        StatusLabel.Text = status ?? string.Empty;
    }

    private void OnClaimTextChanged(LineEdit.LineEditEventArgs args)
    {
        if (args.Text.Length > MaxClaimTextLength)
            args.Control.Text = args.Text[..MaxClaimTextLength];

        UpdateCharCount();
        UpdateSubmitEnabled();
    }

    private void TrySubmit()
    {
        var text = ClaimInput.Text.Trim();
        if (text.Length == 0)
            return;

        if (text.Length > MaxClaimTextLength)
            text = text[..MaxClaimTextLength];

        OnClaimSubmitted?.Invoke(text);

        ClaimInput.Text = string.Empty;
        UpdateCharCount();
        UpdateSubmitEnabled();
    }

    private void UpdateCharCount()
    {
        CharCountLabel.Text = Loc.GetString("solreign-bounties-ui-char-count",
            ("current", ClaimInput.Text.Length), ("max", MaxClaimTextLength));
    }

    private void UpdateSubmitEnabled()
    {
        SubmitButton.Disabled = ClaimInput.Text.Trim().Length == 0;
    }
}
