using Content.Shared._Solreign.Bounties;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Solreign.Bounties.UI;

/// <summary>
///     One row on the Liability Board. Purely presentational — the listing is already
///     server-sanitized (bounded title/description length, capped row count) before it ever
///     reaches this control (see <c>SolreignBountySystem</c>/<c>BountyClaimRules</c>). Plain
///     <c>Label.Text</c> rather than <c>RichTextLabel.SetMarkup</c>: title/description are
///     UNSIGNED daemon display data (this system's public bounty list is never
///     <c>VerifyResponse</c>'d) and must not be interpreted as client-side markup.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SolreignBountyEntry : BoxContainer
{
    public SolreignBountyEntry(SolreignBountyListing listing)
    {
        RobustXamlLoader.Load(this);

        TitleLabel.Text = listing.Title;

        // FromUnformatted, never SetMarkup/Text=: it calls AddText() and parses NOTHING, so the
        // description stays literal. That preserves the property the plain Label was chosen for
        // (see the class doc) while gaining the word-wrap Label lacks — a long claim previously
        // ran off the panel and was unreadable at any window width.
        DescriptionLabel.SetMessage(FormattedMessage.FromUnformatted(listing.Description));
    }
}
