using Content.Client.UserInterface.Controls;
using Content.Shared._Solreign.ShiftArchive;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._Solreign.ShiftArchive;

/// <summary>
///     Dumb list over server-rendered strings — every entry line arrived fully rendered
///     (<c>ShiftArchiveSystem</c> is the only place that calls <c>Loc.GetString</c> for archive
///     copy); the window itself only localizes its own chrome (title, empty and offline states).
///     Lines are <see cref="RichTextLabel"/>s, not <see cref="Label"/>s — Label has no Wrap
///     property and a long directive title would clip (the Corporate window's recorded XAML break).
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ShiftArchiveWindow : FancyWindow
{
    public ShiftArchiveWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("solreign-shift-archive-window-title");
    }

    public void UpdateState(ShiftArchiveState state)
    {
        ArchiveEntriesContainer.RemoveAllChildren();

        if (!state.Enabled)
        {
            AddCenteredNotice(Loc.GetString("solreign-shift-archive-offline"));
            return;
        }

        if (state.Entries.Count == 0)
        {
            AddCenteredNotice(Loc.GetString("solreign-shift-archive-empty"));
            return;
        }

        foreach (var entry in state.Entries)
        {
            var entryBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(10, 10, 10, 5)
            };

            entryBox.AddChild(new Label
            {
                Text = entry.Header,
                FontColorOverride = Color.FromHex("#9acd32")
            });

            foreach (var line in entry.Lines)
            {
                var lineLabel = new RichTextLabel
                {
                    Margin = new Thickness(5, 2, 0, 0)
                };
                lineLabel.SetMessage(FormattedMessage.FromUnformatted(line));
                entryBox.AddChild(lineLabel);
            }

            entryBox.AddChild(new PanelContainer
            {
                StyleClasses = { "LowDivider" },
                Margin = new Thickness(5, 8, 5, 0)
            });

            ArchiveEntriesContainer.AddChild(entryBox);
        }
    }

    private void AddCenteredNotice(string text)
    {
        ArchiveEntriesContainer.AddChild(new Label
        {
            Text = text,
            FontColorOverride = Color.FromHex("#555555"),
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(0, 20)
        });
    }
}
