using System.Numerics;
using Content.Client.Pinpointer.UI;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Map;

namespace Content.Client._Solreign.PlayerDelight.FirstShift.UI;

[GenerateTypedNameReferences]
public sealed partial class FirstShiftMapWindow : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;

    public FirstShiftMapWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public bool SetMarker(NetCoordinates networkCoordinates, bool usedFallback)
    {
        var coordinates = _entityManager.GetCoordinates(networkCoordinates);
        if (!_entityManager.TryGetComponent<TransformComponent>(coordinates.EntityId, out var transform))
            return false;

        var map = transform.GridUid ?? transform.MapUid;
        if (map == null)
            return false;

        NavMap.MapUid = map;
        NavMap.TrackedCoordinates.Clear();
        NavMap.TrackedCoordinates.Add(coordinates, (true, Color.Cyan));
        NavMap.ForceNavMapUpdate();
        NavMap.CenterToCoordinates(coordinates);
        MarkerDescription.Text = Loc.GetString(usedFallback
            ? "first-shift-map-arrivals-marker"
            : "first-shift-map-department-marker");
        return true;
    }

    public void ClearMarker()
    {
        NavMap.TrackedCoordinates.Clear();
        NavMap.MapUid = null;
    }
}
