using System.Linq;
using Content.Client.UserInterface.Systems.Bwoink;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared._Solreign.PlayerDelight.FirstShift;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Solreign.PlayerDelight.FirstShift.UI;

[GenerateTypedNameReferences]
public sealed partial class FirstShiftPanel : Control
{
    [Dependency] private IPrototypeManager _prototypes = default!;

    private static readonly (FirstShiftDepartment Department, string LocKey)[] Departments =
    [
        (FirstShiftDepartment.Engineering, "first-shift-department-engineering"),
        (FirstShiftDepartment.Medical, "first-shift-department-medical"),
        (FirstShiftDepartment.Science, "first-shift-department-science"),
        (FirstShiftDepartment.Cargo, "first-shift-department-cargo"),
        (FirstShiftDepartment.Service, "first-shift-department-service"),
    ];

    private FirstShiftUiState? _state;
    private FirstShiftPresentation? _presentation;
    private ulong _transportGeneration;
    private FirstShiftMapWindow? _mapWindow;

    public event Action<FirstShiftDepartment, ulong>? OnStart;
    public event Action<uint>? OnAdvance;
    public event Action<uint>? OnReroll;
    public event Action<uint>? OnComplete;
    public event Action<uint>? OnEnd;
    public event Action? OnFindCrewmate;

    public FirstShiftPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        foreach (var department in Departments)
            DepartmentOptions.AddItem(Loc.GetString(department.LocKey), (int) department.Department);

        DepartmentOptions.TrySelectId((int) FirstShiftDepartment.Engineering);
        StartButton.OnPressed += _ => OnStart?.Invoke(SelectedDepartment(), _transportGeneration);
        PrimaryButton.OnPressed += _ => EmitPrimary();
        SkipButton.OnPressed += _ => EmitAdvance();
        RerollButton.OnPressed += _ => EmitReroll();
        EndButton.OnPressed += _ => EmitEnd();
        FindCrewmateButton.OnPressed += _ => OnFindCrewmate?.Invoke();
        GuideButton.OnPressed += _ => OpenGuide();
        AHelpButton.OnPressed += _ => UserInterfaceManager.GetUIController<AHelpUIController>().Open();
        MapButton.OnPressed += _ => OpenMap();
        PlainInstructions.OnToggled += _ => UpdateFlavorVisibility();

        Heading.CanKeyboardFocus = true;
        ApplyState(0, FirstShiftUiState.Disabled(FirstShiftDepartment.Universal));
    }

    public void ApplyState(ulong transportGeneration, FirstShiftUiState state)
    {
        if (FirstShiftPresentation.MustDiscardPrivateMarker(state))
            ClearMapMarker();

        var shouldFocus = _state == null || _state.Active != state.Active ||
                          (_state.Active && state.Active && _state.CardId != state.CardId);
        _transportGeneration = transportGeneration;
        _state = state;

        DisabledPanel.Visible = !state.Enabled;
        IdlePanel.Visible = state.Enabled && !state.Active;
        ActivePanel.Visible = state.Enabled && state.Active;

        if (!state.Enabled)
        {
            Status.Text = Loc.GetString("first-shift-disabled");
        }
        else if (!state.Active)
        {
            Status.Text = Loc.GetString("first-shift-idle-intro");
            SuggestedDepartment.Text = Loc.GetString("first-shift-suggested-department",
                ("department", Loc.GetString(FirstShiftPresentation.SuggestionLocKey(state.SuggestedDepartment))));
            if (IsSelectable(state.SuggestedDepartment))
                DepartmentOptions.TrySelectId((int) state.SuggestedDepartment);
        }
        else
        {
            RenderActive(state);
        }

        if (shouldFocus)
            Heading.GrabKeyboardFocus();
    }

    /// <summary>Discards all viewer-private state when the parent BUI lifetime ends.</summary>
    public void ClearPrivateState()
    {
        ClearMapMarker();
        _state = null;
        _presentation = null;
        _transportGeneration = 0;
        TitleLabel.Text = string.Empty;
        WhyLabel.Text = string.Empty;
        OrientLabel.Text = string.Empty;
        TryLabel.Text = string.Empty;
        IfStuckLabel.Text = string.Empty;
        SafetyStopLabel.Text = string.Empty;
        FlavorLabel.Text = string.Empty;
        MarkerStatus.Text = string.Empty;
        TaskListLabel.Text = string.Empty;
        Task4RowLabel.Text = string.Empty;
        Task4DeflectionLabel.Text = string.Empty;
        Task4Panel.Visible = false;
        Task5Panel.Visible = false;
    }

    private void ClearMapMarker()
    {
        if (_mapWindow == null)
            return;

        _mapWindow.ClearMarker();
        _mapWindow.Close();
        _mapWindow = null;
    }

    private void RenderActive(FirstShiftUiState state)
    {
        // These values are localization IDs supplied by the privacy-reviewed server snapshot.
        TitleLabel.Text = Loc.GetString(state.Title);
        WhyLabel.Text = Loc.GetString("first-shift-card-why", ("instruction", Loc.GetString(state.Why)));
        OrientLabel.Text = Loc.GetString("first-shift-card-orient", ("instruction", Loc.GetString(state.Orient)));
        TryLabel.Text = Loc.GetString("first-shift-card-try", ("instruction", Loc.GetString(state.Try)));
        IfStuckLabel.Text = Loc.GetString("first-shift-card-if-stuck", ("instruction", Loc.GetString(state.IfStuck)));
        SafetyStopLabel.Text = Loc.GetString("first-shift-card-safety-stop", ("instruction", Loc.GetString(state.SafetyStop)));
        FlavorLabel.Text = string.IsNullOrWhiteSpace(state.Flavor) ? string.Empty : Loc.GetString(state.Flavor);

        // Kishōtenketsu restructure (MARK-SPEC §3.6): the numbered overview + the permanent Task 4
        // row. Both are pure presentation, gated on the server-mirrored CVar — dormant renders the
        // classic 3-task list with Task 4 absent, exactly as it read before this wave.
        TaskListLabel.Text = string.Join("   ",
            FirstShiftTaskListPresentation.RowKeys(state.MarkEnabled).Select(Loc.GetString));
        Task4Panel.Visible = state.MarkEnabled;
        Task5Panel.Visible = state.MarkEnabled;
        Task4RowLabel.Text = string.IsNullOrWhiteSpace(state.Task4RowKey) ? string.Empty : Loc.GetString(state.Task4RowKey);
        Task4DeflectionLabel.Text = string.IsNullOrWhiteSpace(state.Task4DeflectionKey) ? string.Empty : Loc.GetString(state.Task4DeflectionKey);

        var hasGuide = !string.IsNullOrWhiteSpace(state.GuideEntry) &&
                       _prototypes.TryIndex<GuideEntryPrototype>(state.GuideEntry, out _);
        var presentation = FirstShiftPresentation.For(state.Stage, state.MarkEnabled, state.UsedFallback,
            state.AnchorUnavailable, hasGuide,
            !PlainInstructions.Pressed, !string.IsNullOrWhiteSpace(state.Flavor));
        _presentation = presentation;
        PrimaryButton.Text = Loc.GetString(presentation.PrimaryLocKey);
        SkipButton.Visible = presentation.ShowSkip;
        GuideButton.Disabled = !presentation.CanOpenGuide;
        MapButton.Disabled = !presentation.CanOpenMap || state.Anchor == null;
        // Task 5 (spec §3.6 edit #4): the SAME MarkerStatus/MapButton controls repoint at the
        // Continuity Garden once Stage==Mark — the anchor label/status text already reflects that
        // via FirstShiftPresentation.For's stage-aware branch; no separate marker widget needed.
        MarkerStatus.Text = Loc.GetString(presentation.AnchorStatusLocKey,
            ("label", string.IsNullOrWhiteSpace(state.AnchorLabel) ? Loc.GetString("first-shift-marker-unknown") : Loc.GetString(state.AnchorLabel)));
        // Keep the intent reachable. The server remains authoritative and rejects requests made
        // before its cooldown expires, while this text explains why a click may not change state.
        RerollButton.Disabled = false;
        RerollCooldownLabel.Visible = !state.CanReroll;
        RerollCooldownLabel.Text = state.CanReroll
            ? string.Empty
            : Loc.GetString("first-shift-reroll-cooldown",
                ("seconds", Math.Max(1, (int) Math.Ceiling(state.RerollRemaining.TotalSeconds))));
        UpdateFlavorVisibility();
    }

    private void UpdateFlavorVisibility()
    {
        FlavorPanel.Visible = _state is { Active: true } state &&
                              !PlainInstructions.Pressed &&
                              !string.IsNullOrWhiteSpace(state.Flavor);
    }

    private void EmitPrimary()
    {
        if (_state is not { Active: true } state)
            return;
        // Terminal is whatever the cached presentation says it is (Mark when live, Debrief when
        // dormant — FirstShiftPresentation.For already encodes both), never a raw stage literal.
        if (_presentation is { ShowSkip: false })
            OnComplete?.Invoke(state.Generation);
        else
            OnAdvance?.Invoke(state.Generation);
    }

    private void EmitAdvance()
    {
        if (_state is { Active: true } state && _presentation is { ShowSkip: true })
            OnAdvance?.Invoke(state.Generation);
    }

    private void EmitReroll()
    {
        if (_state is { Active: true } state)
            OnReroll?.Invoke(state.Generation);
    }

    private void EmitEnd()
    {
        if (_state is { Active: true } state)
            OnEnd?.Invoke(state.Generation);
    }

    private void OpenGuide()
    {
        if (_state is not { Active: true } state || string.IsNullOrWhiteSpace(state.GuideEntry) ||
            !_prototypes.TryIndex<GuideEntryPrototype>(state.GuideEntry, out _))
            return;

        var guide = new ProtoId<GuideEntryPrototype>(state.GuideEntry);
        // Explicit initializer, NOT a collection expression: Roslyn lowers List<T> collection
        // expressions via CollectionsMarshal.SetCount, which the SS14 client sandbox bans —
        // the launcher then rejects the whole Content.Client assembly (v10 launch-night bug).
        UserInterfaceManager.GetUIController<GuidebookUIController>()
            .OpenGuidebook(new List<ProtoId<GuideEntryPrototype>> { guide }, selected: guide);
    }

    private void OpenMap()
    {
        if (_state is not { Active: true, Anchor: { } anchor } state || state.AnchorUnavailable)
            return;

        _mapWindow ??= new FirstShiftMapWindow();
        if (!_mapWindow.SetMarker(anchor, state.UsedFallback))
        {
            MapButton.Disabled = true;
            MarkerStatus.Text = Loc.GetString("first-shift-marker-unavailable");
            return;
        }
        _mapWindow.OpenCentered();
    }

    private FirstShiftDepartment SelectedDepartment() =>
        Enum.IsDefined(typeof(FirstShiftDepartment), DepartmentOptions.SelectedId)
            ? (FirstShiftDepartment) DepartmentOptions.SelectedId
            : FirstShiftDepartment.Engineering;

    private static bool IsSelectable(FirstShiftDepartment department) => Departments.Any(x => x.Department == department);

}
