using Content.Client.Message;
using Content.Shared._Solreign.Contracts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Solreign.Contracts.UI;

/// <summary>
///     One work-order card on the Contracts Board. Copies the upstream cargo <c>BountyEntry</c> idiom:
///     resolve the prototype client-side for names/description, render the snapshot the server sent
///     (progress, roster, scaled reward), and count the station-wide skip cooldown down in
///     <see cref="FrameUpdate"/>. Which buttons show is pure presentation — every rule is re-checked
///     server-side, so a stale window can never claim, join, launch or skip anything it shouldn't.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SolreignContractEntry : BoxContainer
{
    [Dependency] private IPrototypeManager _prototype = default!;

    public Action? OnClaimPressed;
    public Action? OnSkipPressed;
    public Action? OnJoinPressed;
    public Action? OnLaunchPressed;

    public TimeSpan UntilNextSkip;

    public SolreignContractEntry(SolreignContractListing listing, TimeSpan untilNextSkip)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        UntilNextSkip = untilNextSkip;

        if (!_prototype.TryIndex<SolreignContractPrototype>(listing.Prototype, out var proto))
            return;

        TitleLabel.SetMarkup(Loc.GetString("solreign-contracts-ui-title-label",
            ("name", Loc.GetString(proto.Name))));
        RewardLabel.SetMarkup(Loc.GetString("solreign-contracts-ui-reward-label",
            ("standing", listing.StandingPerHead)));
        ManifestLabel.SetMarkup(Loc.GetString("solreign-contracts-ui-manifest-label",
            ("items", BuildManifest(listing, proto))));
        StatusLabel.SetMarkup(BuildStatus(listing));
        IdLabel.SetMarkup(Loc.GetString("solreign-contracts-ui-id-label", ("id", listing.Id)));

        if (string.IsNullOrEmpty(proto.Description))
        {
            DescriptionSeparator.Visible = false;
            DescriptionLabel.Visible = false;
        }
        else
        {
            DescriptionLabel.SetMarkup(Loc.GetString("solreign-contracts-ui-description-label",
                ("description", Loc.GetString(proto.Description))));
        }

        // Buttons by scope (presentation only; the server re-validates everything).
        ClaimButton.Visible = listing.Scope == SolreignContractScope.Personal && listing.ClaimantName == null;
        JoinButton.Visible = listing.Scope == SolreignContractScope.SalvageRaid && !listing.Launched;
        LaunchButton.Visible = JoinButton.Visible;

        ClaimButton.OnPressed += _ => OnClaimPressed?.Invoke();
        SkipButton.OnPressed += _ => OnSkipPressed?.Invoke();
        JoinButton.OnPressed += _ => OnJoinPressed?.Invoke();
        LaunchButton.OnPressed += _ => OnLaunchPressed?.Invoke();
    }

    /// <summary>Comma-joined deliverables with live progress, e.g. "cola (3/5), pen (0/10)".</summary>
    private static string BuildManifest(SolreignContractListing listing, SolreignContractPrototype proto)
    {
        var items = new List<string>();
        for (var i = 0; i < proto.Entries.Count; i++)
        {
            // Snapshot lists are parallel to the entries; Required is already raid-scaled server-side.
            var done = i < listing.Progress.Count ? listing.Progress[i] : 0;
            var total = i < listing.Required.Count ? listing.Required[i] : proto.Entries[i].Amount;
            items.Add(Loc.GetString("solreign-contracts-ui-manifest-entry",
                ("item", Loc.GetString(proto.Entries[i].Name)),
                ("done", done),
                ("total", total)));
        }

        return string.Join(", ", items);
    }

    private static string BuildStatus(SolreignContractListing listing)
    {
        return listing.Scope switch
        {
            SolreignContractScope.SalvageRaid when !listing.Launched =>
                Loc.GetString("solreign-contracts-ui-status-recruiting", ("count", listing.Participants)),
            SolreignContractScope.SalvageRaid =>
                Loc.GetString("solreign-contracts-ui-status-launched", ("count", listing.Participants)),
            _ when listing.ClaimantName is { } claimant =>
                Loc.GetString("solreign-contracts-ui-status-claimed", ("claimant", claimant)),
            _ =>
                Loc.GetString("solreign-contracts-ui-status-open"),
        };
    }

    /// <summary>Skip-cooldown countdown on the decline button — the upstream BountyEntry idiom.</summary>
    private void UpdateSkipButton(float deltaSeconds)
    {
        UntilNextSkip -= TimeSpan.FromSeconds(deltaSeconds);
        if (UntilNextSkip > TimeSpan.Zero)
        {
            SkipButton.Label.Text = UntilNextSkip.ToString("mm\\:ss");
            SkipButton.Disabled = true;
            return;
        }

        SkipButton.Label.Text = Loc.GetString("solreign-contracts-ui-skip-button");
        SkipButton.Disabled = false;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateSkipButton(args.DeltaSeconds);
    }
}
