using Content.Client.UserInterface.Controls;
using Content.Shared._Solreign.Contracts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Solreign.Contracts.UI;

/// <summary>
///     The Contracts Board window body: rebuilds the card list on every state push, the upstream
///     <c>CargoBountyMenu.UpdateEntries</c> idiom. Per-card buttons bubble up as string-id events for the
///     BUI to turn into messages.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SolreignContractsBoardMenu : FancyWindow
{
    public Action<string>? OnClaimPressed;
    public Action<string>? OnSkipPressed;
    public Action<string>? OnJoinPressed;
    public Action<string>? OnLaunchPressed;

    public SolreignContractsBoardMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateEntries(List<SolreignContractListing> contracts, TimeSpan untilNextSkip)
    {
        ContractEntriesContainer.Children.Clear();
        NoContractsLabel.Visible = contracts.Count == 0;

        foreach (var listing in contracts)
        {
            var entry = new SolreignContractEntry(listing, untilNextSkip);
            entry.OnClaimPressed += () => OnClaimPressed?.Invoke(listing.Id);
            entry.OnSkipPressed += () => OnSkipPressed?.Invoke(listing.Id);
            entry.OnJoinPressed += () => OnJoinPressed?.Invoke(listing.Id);
            entry.OnLaunchPressed += () => OnLaunchPressed?.Invoke(listing.Id);

            ContractEntriesContainer.AddChild(entry);
        }

        ContractEntriesContainer.AddChild(new Control
        {
            MinHeight = 10
        });
    }
}
