using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.Bwoink;
using Content.Shared._Solreign.PlayerDelight.FirstShift;
using Content.Shared._Solreign.PlayerDelight.Wingmates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Solreign.PlayerDelight.Wingmates.UI;

[GenerateTypedNameReferences]
public sealed partial class WingmateWindow : FancyWindow
{
    private static readonly (string Id, string LocKey)[] Departments =
    [
        ("Engineering", "wingmates-department-engineering"),
        ("Medical", "wingmates-department-medical"),
        ("Service", "wingmates-department-service"),
        ("Science", "wingmates-department-science"),
        ("Security", "wingmates-department-security"),
        ("Cargo", "wingmates-department-cargo"),
        ("Command", "wingmates-department-command"),
    ];

    private WingmateUiState? _state;

    public event Action<string, WingmateTeachingMode>? OnRequest;
    public event Action? OnCancelRequest;
    public event Action<Guid>? OnOffer;
    public event Action<Guid>? OnAccept;
    public event Action<Guid, bool>? OnDecline;
    public event Action? OnDissolve;
    public event Action? OnPause;
    public event Action? OnResume;
    public event Action? OnBlock;
    public event Action<bool, bool>? OnVolunteer;
    public event Action<FirstShiftDepartment, ulong>? OnFirstShiftStart;
    public event Action<uint>? OnFirstShiftAdvance;
    public event Action<uint>? OnFirstShiftReroll;
    public event Action<uint>? OnFirstShiftComplete;
    public event Action<uint>? OnFirstShiftEnd;

    public WingmateWindow()
    {
        RobustXamlLoader.Load(this);

        PlayerDelightTabs.SetTabTitle(0, Loc.GetString("first-shift-tab-title"));
        PlayerDelightTabs.SetTabTitle(1, Loc.GetString("wingmates-tab-title"));
        FirstShiftPanel.OnStart += (department, generation) => OnFirstShiftStart?.Invoke(department, generation);
        FirstShiftPanel.OnAdvance += generation => OnFirstShiftAdvance?.Invoke(generation);
        FirstShiftPanel.OnReroll += generation => OnFirstShiftReroll?.Invoke(generation);
        FirstShiftPanel.OnComplete += generation => OnFirstShiftComplete?.Invoke(generation);
        FirstShiftPanel.OnEnd += generation => OnFirstShiftEnd?.Invoke(generation);
        FirstShiftPanel.OnFindCrewmate += () => PlayerDelightTabs.CurrentTab = 1;

        foreach (var department in Departments)
            DepartmentOptions.AddItem(Loc.GetString(department.LocKey));
        DepartmentOptions.TrySelectId(0);

        TeachingModeOptions.AddItem(Loc.GetString("wingmates-teaching-tour"), (int) WingmateTeachingMode.Tour);
        TeachingModeOptions.AddItem(Loc.GetString("wingmates-teaching-learn-by-doing"), (int) WingmateTeachingMode.LearnByDoing);
        TeachingModeOptions.AddItem(Loc.GetString("wingmates-teaching-shadow"), (int) WingmateTeachingMode.ShadowMe);
        TeachingModeOptions.TrySelectId((int) WingmateTeachingMode.LearnByDoing);

        foreach (var termKey in WingmateVolunteerCharter.TermKeys)
            CharterTerms.AddChild(new Label { Text = Loc.GetString(termKey) });

        RequestButton.OnPressed += _ => OnRequest?.Invoke(
            Departments[DepartmentOptions.SelectedId].Id,
            (WingmateTeachingMode) TeachingModeOptions.SelectedId);
        CancelRequestButton.OnPressed += _ => OnCancelRequest?.Invoke();
        OfferButton.OnPressed += _ => EmitOffer();
        AcceptButton.OnPressed += _ => EmitAccept();
        DeclineButton.OnPressed += _ => EmitDecline();
        DissolveButton.OnPressed += _ => OnDissolve?.Invoke();
        PauseButton.OnPressed += _ => OnPause?.Invoke();
        ResumeButton.OnPressed += _ => OnResume?.Invoke();
        BlockButton.OnPressed += _ => EmitBlock();
        VolunteerButton.OnPressed += _ => EmitVolunteer();
        CharterAccepted.OnToggled += _ => UpdateVolunteerButtonState();
        ModeratorHelpButton.OnPressed += _ => UserInterfaceManager.GetUIController<AHelpUIController>().Open();
        CloseWindowButton.OnPressed += _ => Close();

        StateHeading.CanKeyboardFocus = true;
    }

    public void UpdateState(WingmateUiState state)
    {
        var shouldFocus = _state == null || _state.Mode != state.Mode;
        // A new offer nonce means this is a different proposal than whatever the checkbox was last
        // set for; never carry a stale "block" intent forward onto an unrelated guide's offer.
        var offerChanged = _state?.OfferNonce != state.OfferNonce;
        _state = state;
        if (offerChanged)
            BlockDeclinedGuide.Pressed = false;
        var presentation = WingmatePresentation.For(state.Mode);

        RequestPanel.Visible = presentation.ShowRequest;
        WaitingPanel.Visible = presentation.ShowWaiting;

        // ALIVENESS P0 #3: while seeking with no plausible peer connected, the open-ended
        // "your request is open" framing is a trap — swap in the honest no-crew copy (the
        // request itself stays open server-side; a joining player restores the normal view on
        // the next snapshot).
        WaitingConsentLabel.Visible = state.PeerAvailable;
        WaitingFallbackLabel.Visible = state.PeerAvailable;
        WaitingPromptLabel.Visible = state.PeerAvailable;
        NoPeersLabel.Visible = !state.PeerAvailable;
        NoPeersSuggestionLabel.Visible = !state.PeerAvailable;
        OfferPanel.Visible = presentation.ShowOffer;
        ProposalPanel.Visible = presentation.ShowProposal;
        PairPanel.Visible = presentation.ShowPair;
        DisabledPanel.Visible = presentation.ShowDisabled;
        DissolveButton.Visible = presentation.ShowDissolve;
        BlockButton.Visible = presentation.ShowBlock;
        ModeratorHelpButton.Visible = presentation.ShowModeratorHelp;
        PauseButton.Visible = presentation.ShowPause;
        ResumeButton.Visible = presentation.ShowResume;
        VolunteerPanel.Visible = presentation.ShowVolunteer;
        CharterAccepted.Visible = presentation.ShowVolunteer && !state.IsVolunteering;

        StateHeading.Text = Loc.GetString(HeadingKeyFor(state.Mode));
        StatusLabel.Text = Loc.GetString(state.StatusText);
        RequestContextLabel.Text = Loc.GetString("wingmates-request-context",
            ("name", state.RequesterDisplayName ?? Loc.GetString("wingmates-fallback-crewmember")),
            ("department", Loc.GetString(DepartmentKeyFor(state.Department))),
            ("style", Loc.GetString(TeachingModeKey(state.TeachingMode))));
        ProposalLabel.Text = Loc.GetString("wingmates-proposal",
            ("name", state.PartnerDisplayName ?? Loc.GetString("wingmates-fallback-guide")));
        PartnerLabel.Text = Loc.GetString("wingmates-partner",
            ("name", state.PartnerDisplayName ?? Loc.GetString("wingmates-fallback-crewmate")));

        RequestButton.Disabled = !state.CanRequest;
        VolunteerButton.Text = Loc.GetString(state.IsVolunteering
            ? "wingmates-volunteer-opt-out"
            : "wingmates-volunteer-opt-in");
        UpdateVolunteerButtonState();

        // FIX 1 (UX-SIMPLE): never leave a disabled Volunteer button unexplained. The reason label
        // only ever shows while opted OUT and blocked — once volunteering, the button always stays
        // reachable to opt back out (see CanSubmitVolunteerChange), so there is nothing to explain.
        VolunteerIneligibleLabel.Visible = !state.IsVolunteering && state.VolunteerIneligibleReason != null;
        if (state.VolunteerIneligibleReason != null)
            VolunteerIneligibleLabel.Text = Loc.GetString(state.VolunteerIneligibleReason);
        OfferButton.Disabled = !state.CanVolunteer || state.RequesterToken == null;
        AcceptButton.Disabled = state.OfferNonce == null;
        DeclineButton.Disabled = state.OfferNonce == null;
        BlockButton.Disabled = state.Mode is not (WingmateUiMode.Paired or WingmateUiMode.Paused);

        if (shouldFocus)
            StateHeading.GrabKeyboardFocus();
    }

    public void UpdateFirstShiftState(ulong transportGeneration, FirstShiftUiState state)
    {
        FirstShiftPanel.ApplyState(transportGeneration, state);
    }

    public void ClearFirstShiftPrivateState()
    {
        FirstShiftPanel.ClearPrivateState();
    }

    private void EmitOffer()
    {
        if (_state?.RequesterToken is { } requesterToken)
            OnOffer?.Invoke(requesterToken);
    }

    private void EmitAccept()
    {
        if (_state?.OfferNonce is { } nonce)
            OnAccept?.Invoke(nonce);
    }

    private void EmitDecline()
    {
        if (_state?.OfferNonce is { } nonce)
            OnDecline?.Invoke(nonce, BlockDeclinedGuide.Pressed);
    }

    private void EmitBlock() => OnBlock?.Invoke();

    private void EmitVolunteer()
    {
        if (_state == null) return;
        OnVolunteer?.Invoke(!_state.IsVolunteering, CharterAccepted.Pressed);
    }

    private void UpdateVolunteerButtonState()
    {
        if (_state == null)
        {
            VolunteerButton.Disabled = true;
            return;
        }

        // Opt-out stays reachable even if moderator eligibility changes after consent.
        VolunteerButton.Disabled = !WingmatePresentation.CanSubmitVolunteerChange(
            _state.CanVolunteer,
            _state.IsVolunteering,
            CharterAccepted.Pressed);
    }

    private static string HeadingKeyFor(WingmateUiMode mode) => mode switch
    {
        WingmateUiMode.Idle => "wingmates-heading-idle",
        WingmateUiMode.Seeking => "wingmates-heading-seeking",
        WingmateUiMode.OfferAvailable => "wingmates-heading-offer-available",
        WingmateUiMode.OfferReceived => "wingmates-heading-offer-received",
        WingmateUiMode.Paired => "wingmates-heading-paired",
        WingmateUiMode.Paused => "wingmates-heading-paused",
        WingmateUiMode.Disabled => "wingmates-heading-disabled",
        _ => throw new ArgumentOutOfRangeException(nameof(mode), mode, null),
    };

    private static string TeachingModeKey(WingmateTeachingMode mode) => mode switch
    {
        WingmateTeachingMode.Tour => "wingmates-teaching-tour",
        WingmateTeachingMode.LearnByDoing => "wingmates-teaching-learn-by-doing",
        WingmateTeachingMode.ShadowMe => "wingmates-teaching-shadow",
        _ => throw new ArgumentOutOfRangeException(nameof(mode), mode, null),
    };

    private static string DepartmentKeyFor(string department) => Departments
        .FirstOrDefault(entry => entry.Id == department).LocKey ?? "wingmates-department-unknown";
}
