using Content.Client.UserInterface.Controls;
using Content.Shared._Solreign.Memorial;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using System.Text;

namespace Content.Client._Solreign.Memorial;

[GenerateTypedNameReferences]
public sealed partial class MemorialConsoleWindow : FancyWindow
{
    public MemorialConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(MemorialConsoleState state)
    {
        MemorialEntriesContainer.RemoveAllChildren();

        if (state.Records.Count == 0)
        {
            MemorialEntriesContainer.AddChild(new Label
            {
                Text = "NO CRYPT ENTRIES FOUND.",
                FontColorOverride = Color.FromHex("#555555"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 20)
            });
            return;
        }

        foreach (var record in state.Records)
        {
            var entryBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(10, 10, 10, 15)
            };

            var headerLabel = new Label
            {
                Text = $"[ {record.DiedAtUtc} ] // {record.CharacterName.ToUpperInvariant()}",
                FontColorOverride = Color.FromHex("#e65a5a")
            };

            var detailsText = new StringBuilder();
            detailsText.AppendLine($"TITLE: {record.TitleAtDeath} | TOURS: {record.ToursAtDeath}");
            detailsText.AppendLine($"CAUSE: {record.Cause}");
            detailsText.AppendLine($"EPITAPH: {record.EpitaphId}");

            var detailsLabel = new Label
            {
                Text = detailsText.ToString(),
                FontColorOverride = Color.FromHex("#888888"),
                Margin = new Thickness(5, 5, 0, 0)
            };

            entryBox.AddChild(headerLabel);
            entryBox.AddChild(detailsLabel);

            var separator = new PanelContainer
            {
                StyleClasses = { "LowDivider" },
                Margin = new Thickness(5, 5, 5, 0)
            };
            entryBox.AddChild(separator);

            MemorialEntriesContainer.AddChild(entryBox);
        }
    }
}
