using System;
using Content.Client._Solreign.Report;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.Bwoink;
using Content.Shared._Solreign.Report;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Utility;

namespace Content.Client._Solreign.Report.UI;

/// <summary>
///     Body of the "report" window: target LineEdit + category dropdown + short free-text box + Submit,
///     plus a permanently-visible "need urgent help instead? open ahelp" link -- this quick-action is a
///     fast, low-friction triage flag that lands in an admin-visible log, not a live conversation with
///     staff, so a player who needs immediate two-way help is still pointed at ahelp rather than left
///     waiting on this to be seen. Layout/idiom copies
///     <c>Content.Client._Solreign.Feedback.UI.FeedbackWindow</c> (itself modeled on
///     <c>Content.Client.NukeOps.WarDeclaratorWindow</c>).
///
///     No server-truth state to sync here -- one-shot request/response, so the window just fires
///     <see cref="OnSubmitPressed"/> and later gets told the outcome via <see cref="ShowResult"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ReportWindow : FancyWindow
{
    [Dependency] private IUserInterfaceManager _userInterfaceManager = default!;

    /// <summary>Raised when the player presses Submit with a target, chosen category, and (already-typed) text.</summary>
    public event Action<string, ReportCategory, string>? OnSubmitPressed;

    public ReportWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        foreach (var category in Enum.GetValues<ReportCategory>())
        {
            var id = CategorySelector.ItemCount;
            CategorySelector.AddItem(Loc.GetString($"report-category-{category.ToString().ToLowerInvariant()}"));
            CategorySelector.SetItemMetadata(id, category);
        }

        CategorySelector.SelectId(0);

        TextEdit.Placeholder = new Rope.Leaf(Loc.GetString("report-window-text-placeholder"));
        TextEdit.OnTextChanged += _ => UpdateLengthLabel();
        UpdateLengthLabel();

        SubmitButton.OnPressed += _ => Submit();
        SafetyButton.OnPressed += _ => _userInterfaceManager.GetUIController<AHelpUIController>().Open();
    }

    /// <summary>Pre-fills the target field (e.g. from <c>report &lt;name&gt;</c>) without clobbering an in-progress reason.</summary>
    public void SetTarget(string target)
    {
        TargetEdit.Text = target;
    }

    private void UpdateLengthLabel()
    {
        var length = TextEdit.TextLength;
        LengthLabel.Text = Loc.GetString(
            "report-window-length",
            ("length", length),
            ("max", ReportConstants.MaxTextLength));
    }

    private void Submit()
    {
        var target = TargetEdit.Text.Trim();
        if (string.IsNullOrWhiteSpace(target))
        {
            StatusLabel.Text = Loc.GetString("report-no-target");
            return;
        }

        var text = Rope.Collapse(TextEdit.TextRope).Trim();
        if (string.IsNullOrWhiteSpace(text))
        {
            StatusLabel.Text = Loc.GetString("report-empty");
            return;
        }

        if (CategorySelector.SelectedMetadata is not ReportCategory category)
            category = ReportCategory.Griefing;

        SubmitButton.Disabled = true;
        StatusLabel.Text = Loc.GetString("report-window-sending");

        OnSubmitPressed?.Invoke(target, category, text);
    }

    /// <summary>Called by <see cref="ReportClientSystem"/> once the server replies.</summary>
    public void ShowResult(bool success, string? referenceId, string? errorMessage)
    {
        SubmitButton.Disabled = false;

        if (success)
        {
            StatusLabel.Text = Loc.GetString("report-window-success", ("reference", referenceId ?? "?"));
            TextEdit.TextRope = new Rope.Leaf("");
            UpdateLengthLabel();
        }
        else
        {
            StatusLabel.Text = errorMessage ?? Loc.GetString("report-window-unknown-error");
        }
    }
}
