using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Solreign.Oracle.UI;

/// <summary>
///     The Directive Terminal window body: one input, one button, one local confirmation label.
///     Mirrors the <c>NavMapBeaconWindow</c>/<c>PaperWindow</c> idiom for live length-limited text
///     entry (truncate-on-change + a disabled-until-valid send affordance) rather than the
///     Contracts Board's per-state-push rebuild, since this window has no server state to render.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SolreignOracleWindow : FancyWindow
{
    /// <summary>
    ///     Mirrors <c>SolreignOracleSystem.MaxPlayerMessageLength</c> (Content.Server). Client
    ///     enforcement here is a UX convenience only, never the authority — the server truncates
    ///     independently regardless of what this window sends (see that const's doc comment).
    /// </summary>
    public const int MaxMessageLength = 500;

    public event Action<string>? OnSendPressed;

    public SolreignOracleWindow()
    {
        RobustXamlLoader.Load(this);

        MessageInput.OnTextChanged += OnMessageTextChanged;
        MessageInput.OnTextEntered += _ => TrySend();
        SendButton.OnPressed += _ => TrySend();

        UpdateCharCount();
        UpdateSendEnabled();
    }

    private void OnMessageTextChanged(LineEdit.LineEditEventArgs args)
    {
        if (args.Text.Length > MaxMessageLength)
            args.Control.Text = args.Text[..MaxMessageLength];

        // A fresh edit means the last "transmitted" confirmation no longer describes what's in
        // the box; hide it until the next successful send.
        SentLabel.Visible = false;

        UpdateCharCount();
        UpdateSendEnabled();
    }

    private void TrySend()
    {
        var text = MessageInput.Text.Trim();
        if (text.Length == 0)
            return;

        if (text.Length > MaxMessageLength)
            text = text[..MaxMessageLength];

        OnSendPressed?.Invoke(text);

        MessageInput.Text = string.Empty;
        UpdateCharCount();
        UpdateSendEnabled();

        SentLabel.Visible = true;
    }

    private void UpdateCharCount()
    {
        CharCountLabel.Text = Loc.GetString("solreign-oracle-ui-char-count",
            ("current", MessageInput.Text.Length), ("max", MaxMessageLength));
    }

    private void UpdateSendEnabled()
    {
        SendButton.Disabled = MessageInput.Text.Trim().Length == 0;
    }
}
