using System;
using Content.Client._Solreign.Feedback;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.Bwoink;
using Content.Shared._Solreign.Feedback;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Utility;

namespace Content.Client._Solreign.Feedback.UI;

/// <summary>
///     Body of the "feedback" window (roadmap D2.1). Category dropdown + free-text box + Submit,
///     plus a permanently-visible "report a safety concern instead" link straight to ahelp -- the
///     roadmap is explicit that product feedback must never substitute for ahelp/moderation, so that
///     route lives beside the form rather than behind another command a distressed player has to know.
///
///     No server-truth state to sync here (unlike <c>SolreignContractsBoardMenu</c>) -- this is a
///     one-shot request/response, so the window just fires <see cref="OnSubmitPressed"/> and later gets
///     told the outcome via <see cref="ShowResult"/>. Layout/idiom (TextEdit + Rope.Collapse, plain
///     Button) copies <c>Content.Client.NukeOps.WarDeclaratorWindow</c>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class FeedbackWindow : FancyWindow
{
    [Dependency] private IUserInterfaceManager _userInterfaceManager = default!;

    /// <summary>Raised when the player presses Submit with a chosen category and (already-typed) text.</summary>
    public event Action<FeedbackCategory, string>? OnSubmitPressed;

    public FeedbackWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        foreach (var category in Enum.GetValues<FeedbackCategory>())
        {
            var id = CategorySelector.ItemCount;
            CategorySelector.AddItem(Loc.GetString($"feedback-category-{category.ToString().ToLowerInvariant()}"));
            CategorySelector.SetItemMetadata(id, category);
        }

        CategorySelector.SelectId(0);

        TextEdit.Placeholder = new Rope.Leaf(Loc.GetString("feedback-window-text-placeholder"));
        TextEdit.OnTextChanged += _ => UpdateLengthLabel();
        UpdateLengthLabel();

        SubmitButton.OnPressed += _ => Submit();
        SafetyButton.OnPressed += _ => _userInterfaceManager.GetUIController<AHelpUIController>().Open();
    }

    private void UpdateLengthLabel()
    {
        var length = TextEdit.TextLength;
        LengthLabel.Text = Loc.GetString(
            "feedback-window-length",
            ("length", length),
            ("max", FeedbackConstants.MaxTextLength));
    }

    private void Submit()
    {
        var text = Rope.Collapse(TextEdit.TextRope).Trim();
        if (string.IsNullOrWhiteSpace(text))
        {
            StatusLabel.Text = Loc.GetString("feedback-empty");
            return;
        }

        if (CategorySelector.SelectedMetadata is not FeedbackCategory category)
            category = FeedbackCategory.Bug;

        SubmitButton.Disabled = true;
        StatusLabel.Text = Loc.GetString("feedback-window-sending");

        OnSubmitPressed?.Invoke(category, text);
    }

    /// <summary>Called by <see cref="FeedbackClientSystem"/> once the server replies.</summary>
    public void ShowResult(bool success, string? referenceId, string? errorMessage)
    {
        SubmitButton.Disabled = false;

        if (success)
        {
            StatusLabel.Text = Loc.GetString("feedback-window-success", ("reference", referenceId ?? "?"));
            TextEdit.TextRope = new Rope.Leaf("");
            UpdateLengthLabel();
        }
        else
        {
            StatusLabel.Text = errorMessage ?? Loc.GetString("feedback-window-unknown-error");
        }
    }
}
