using System;
using System.Collections.Generic;
using Content.Client.UserInterface.Controls;
using Content.Shared._Solreign.Corporate.Projects;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._Solreign.Corporate.Projects.UI;

[GenerateTypedNameReferences]
public sealed partial class SolreignCorporateProjectWindow : FancyWindow
{
    public Action<string, int>? OnContributePressed;
    public Action<string>? OnProjectSelected;

    private string? _selectedProjectId;
    private SolreignCorporateProjectState? _selectedProject;

    public SolreignCorporateProjectWindow()
    {
        RobustXamlLoader.Load(this);

        ContributeButton.OnPressed += _ =>
        {
            if (_selectedProjectId == null)
                return;

            if (int.TryParse(AmountInput.Text, out var amount) && amount > 0)
            {
                OnContributePressed?.Invoke(_selectedProjectId, amount);
            }
        };
    }

    public void UpdateState(SolreignCorporateProjectUiState state)
    {
        _selectedProjectId = state.SelectedProjectId;
        ProjectListContainer.Children.Clear();
        MilestonesContainer.Children.Clear();

        if (state.StatusMessage != null)
        {
            StatusLabel.Text = state.StatusMessage;
        }

        foreach (var proj in state.Projects)
        {
            var btn = new Button
            {
                Text = proj.Name,
                ToggleMode = true,
                Pressed = proj.ProjectId == _selectedProjectId
            };

            var projId = proj.ProjectId;
            btn.OnPressed += _ =>
            {
                _selectedProjectId = projId;
                OnProjectSelected?.Invoke(projId);
            };

            ProjectListContainer.AddChild(btn);

            if (proj.ProjectId == _selectedProjectId)
            {
                _selectedProject = proj;
            }
        }

        if (_selectedProject != null)
        {
            ProjectNameLabel.Text = _selectedProject.Name;
            SponsorLabel.Text = Loc.GetString("solreign-corporate-projects-sponsor-label", ("sponsor", _selectedProject.Sponsor));
            DescriptionLabel.SetMessage(_selectedProject.Description);

            float pct = _selectedProject.TargetContribution > 0
                ? (float) _selectedProject.CurrentContribution / _selectedProject.TargetContribution
                : 0f;

            OverallProgressBar.Value = Math.Clamp(pct, 0f, 1f);

            int pctInt = (int) Math.Floor(pct * 100);
            ProgressLabel.Text = Loc.GetString("solreign-corporate-projects-progress-label",
                ("current", _selectedProject.CurrentContribution),
                ("target", _selectedProject.TargetContribution),
                ("percent", pctInt));

            int acctPctInt = _selectedProject.MaxAccountContribution > 0
                ? (int) Math.Floor(((float) _selectedProject.AccountContribution / _selectedProject.MaxAccountContribution) * 100)
                : 0;

            AccountShareLabel.Text = Loc.GetString("solreign-corporate-projects-account-share-label",
                ("accountCurrent", _selectedProject.AccountContribution),
                ("accountCap", _selectedProject.MaxAccountContribution),
                ("accountPercent", acctPctInt));

            ContributeButton.Disabled = _selectedProject.Completed || _selectedProject.AccountContribution >= _selectedProject.MaxAccountContribution;

            foreach (var m in _selectedProject.Milestones)
            {
                int threshPct = (int) Math.Floor(m.ThresholdFraction * 100);
                string statusText = m.Unlocked ? "UNLOCKED" : "LOCKED";

                var itemLabel = new Label
                {
                    Text = Loc.GetString("solreign-corporate-projects-milestone-item",
                        ("status", statusText),
                        ("threshold", threshPct),
                        ("name", m.Name),
                        ("standing", m.StandingReward))
                };

                MilestonesContainer.AddChild(itemLabel);
            }
        }
    }
}
