using System;
using Content.Shared._Solreign.Noticeboards;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Solreign.Noticeboards.UI;

/// <summary>
///     One row on the crew Noticeboard. Purely presentational — the note has already passed the
///     daemon classifier and every server-side length/quota check before it ever reaches this
///     control. A PROVIDENCE-authored row gets a visually distinct author line (spec rule 5: never
///     blended in as if a player wrote it) — plain color/weight distinction here rather than a
///     separate icon asset, since this lane ships no new art.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SolreignNoticeboardEntry : BoxContainer
{
    public event Action? OnReportPressed;

    public SolreignNoticeboardEntry(SolreignNoticeboardNoteView note)
    {
        RobustXamlLoader.Load(this);

        AuthorLabel.Text = note.AuthorDisplay;
        if (note.IsProvidence)
            AuthorLabel.FontColorOverride = Color.FromHex("#7FDBFF");

        BodyLabel.Text = note.Text;
        ReportButton.Text = Loc.GetString("solreign-noticeboards-ui-report-button");
        ReportButton.OnPressed += _ => OnReportPressed?.Invoke();
    }
}
