using System;
using System.Collections.Generic;
using Content.Client.UserInterface.Controls;
using Content.Shared._Solreign.Noticeboards;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Solreign.Noticeboards.UI;

/// <summary>
///     The crew Noticeboard window body. Two independent update surfaces driven by the same
///     <see cref="SolreignNoticeboardUiState"/> push: the note list (Liability Board
///     <c>UpdateEntries</c> idiom — rebuild on every state) and the post input (live length clamp
///     + disabled-until-valid submit, the same idiom). Client-side clamping here is UX only; the
///     server enforces the real cap independently (see <c>NoticeboardRules.MaxNoteLength</c>).
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SolreignNoticeboardWindow : FancyWindow
{
    /// <summary>Mirrors <c>NoticeboardRules.MaxNoteLength</c> (Content.Server) — UX convenience only, never the authority.</summary>
    public const int MaxNoteTextLength = 260;

    public event Action<string>? OnNoteSubmitted;

    public event Action<int>? OnNoteReported;

    public SolreignNoticeboardWindow()
    {
        RobustXamlLoader.Load(this);

        PostInput.OnTextChanged += OnPostTextChanged;
        PostInput.OnTextEntered += _ => TrySubmit();
        SubmitButton.OnPressed += _ => TrySubmit();

        UpdateCharCount();
        UpdateSubmitEnabled();
    }

    public void UpdateState(List<SolreignNoticeboardNoteView> notes, string? status, bool offline = false)
    {
        NoteEntriesContainer.Children.Clear();

        NoNotesLabel.Visible = !offline && notes.Count == 0;
        OfflineLabel.Visible = offline;

        foreach (var note in notes)
        {
            var entry = new SolreignNoticeboardEntry(note);
            var noteId = note.Id;
            entry.OnReportPressed += () => OnNoteReported?.Invoke(noteId);
            NoteEntriesContainer.AddChild(entry);
        }

        NoteEntriesContainer.AddChild(new Control
        {
            MinHeight = 10
        });

        StatusLabel.Visible = !string.IsNullOrEmpty(status);
        StatusLabel.Text = status ?? string.Empty;
    }

    private void OnPostTextChanged(LineEdit.LineEditEventArgs args)
    {
        if (args.Text.Length > MaxNoteTextLength)
            args.Control.Text = args.Text[..MaxNoteTextLength];

        UpdateCharCount();
        UpdateSubmitEnabled();
    }

    private void TrySubmit()
    {
        var text = PostInput.Text.Trim();
        if (text.Length == 0)
            return;

        if (text.Length > MaxNoteTextLength)
            text = text[..MaxNoteTextLength];

        OnNoteSubmitted?.Invoke(text);

        PostInput.Text = string.Empty;
        UpdateCharCount();
        UpdateSubmitEnabled();
    }

    private void UpdateCharCount()
    {
        CharCountLabel.Text = Loc.GetString("solreign-noticeboards-ui-char-count",
            ("current", PostInput.Text.Length), ("max", MaxNoteTextLength));
    }

    private void UpdateSubmitEnabled()
    {
        SubmitButton.Disabled = PostInput.Text.Trim().Length == 0;
    }
}
